<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Rased.Domain\Rased.Domain.csproj" />
    <ProjectReference Include="..\Rased.Services Abstraction\Rased.Services Abstraction.csproj" />
  </ItemGroup>

</Project>
